return {
  'bash-language-server',
  'clangd',
  'css-lsp',
  'docker-compose-language-service',
  'dockerfile-language-server',
  'eslint-lsp',
  'gopls',
  'html-lsp',
  'jdtls',
  'json-lsp',
  'lua-language-server',
  'marksman',
  'pyright',
  'texlab',
  'typescript-language-server',
}
