config-version = 2

after-startup-command = []

start-at-login = true

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 0

default-root-container-layout = 'tiles'

default-root-container-orientation = 'auto'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

automatically-unhide-macos-hidden-apps = true

persistent-workspaces = [
    '1', # Browser
    '2', # Email
    '3', # Development
    '4', # Slack
    '5', # Notes
    '6', # Zoom
    '7', # Misc
    '8',
    '9',
]

on-focus-changed = ['move-mouse window-lazy-center']

[exec.env-vars]
    PATH = '${HOME}/.local/bin:/opt/homebrew/bin:/opt/homebrew/sbin:${PATH}'

[[on-window-detected]]
    if.app-id = 'org.mozilla.firefox'
    if.during-aerospace-startup = true
    run = ['move-node-to-workspace 1', 'workspace 1']

[[on-window-detected]]
    if.app-id = 'com.microsoft.Outlook'
    if.during-aerospace-startup = true
    run = ['move-node-to-workspace 2', 'workspace 2']

[[on-window-detected]]
    if.app-id = 'com.github.wez.wezterm'
    if.during-aerospace-startup = true
    run = ['move-node-to-workspace 3', 'workspace 3']

[[on-window-detected]]
    if.app-id = 'com.tinyspeck.slackmacgap'
    if.during-aerospace-startup = true
    run = ['move-node-to-workspace 4', 'workspace 4']

[[on-window-detected]]
    if.app-id = 'md.obsidian'
    if.during-aerospace-startup = true
    run = ['move-node-to-workspace 5', 'workspace 5']

[[on-window-detected]]
    if.app-name-regex-substring = 'zoom\.us'
    run = ['move-node-to-workspace 6', 'workspace 6', 'layout floating']

[[on-window-detected]]
    if.app-id = 'com.anthropic.claudefordesktop'
    run = ['layout floating']

[key-mapping]
    preset = 'qwerty'

[gaps]
    inner.horizontal = 2
    inner.vertical =   2
    outer.left =       2
    outer.bottom =     2
    outer.top =        2
    outer.right =      2

[mode.main.binding]
    ctrl-alt-shift-x = 'exec-and-forget open /System/Applications/System\ Settings.app'
    ctrl-alt-shift-o = 'exec-and-forget open /Applications/Microsoft\ Outlook.app'
    ctrl-alt-shift-e = 'exec-and-forget open /System/Library/CoreServices/Finder.app'
    ctrl-alt-shift-c = 'exec-and-forget open /Applications/Claude.app'

    ctrl-alt-shift-f = 'fullscreen'

    ctrl-alt-shift-slash = 'layout tiles horizontal vertical'
    ctrl-alt-shift-comma = 'layout accordion horizontal vertical'

    ctrl-alt-shift-h = 'focus left'
    ctrl-alt-shift-j = 'focus down'
    ctrl-alt-shift-k = 'focus up'
    ctrl-alt-shift-l = 'focus right'

    ctrl-alt-shift-cmd-h = 'move left'
    ctrl-alt-shift-cmd-j = 'move down'
    ctrl-alt-shift-cmd-k = 'move up'
    ctrl-alt-shift-cmd-l = 'move right'

    ctrl-alt-shift-minus = 'resize smart -50'
    ctrl-alt-shift-equal = 'resize smart +50'

    ctrl-alt-shift-1 = 'workspace 1'
    ctrl-alt-shift-2 = 'workspace 2'
    ctrl-alt-shift-3 = 'workspace 3'
    ctrl-alt-shift-4 = 'workspace 4'
    ctrl-alt-shift-5 = 'workspace 5'
    ctrl-alt-shift-6 = 'workspace 6'
    ctrl-alt-shift-7 = 'workspace 7'
    ctrl-alt-shift-8 = 'workspace 8'
    ctrl-alt-shift-9 = 'workspace 9'

    ctrl-alt-shift-tab = 'workspace-back-and-forth'

    ctrl-alt-shift-cmd-1 = ['move-node-to-workspace 1', 'workspace 1', 'layout tiling']
    ctrl-alt-shift-cmd-2 = ['move-node-to-workspace 2', 'workspace 2', 'layout floating']
    ctrl-alt-shift-cmd-3 = ['move-node-to-workspace 3', 'workspace 3', 'layout tiling']
    ctrl-alt-shift-cmd-4 = ['move-node-to-workspace 4', 'workspace 4', 'layout tiling']
    ctrl-alt-shift-cmd-5 = ['move-node-to-workspace 5', 'workspace 5', 'layout tiling']
    ctrl-alt-shift-cmd-6 = ['move-node-to-workspace 6', 'workspace 4', 'layout floating']
    ctrl-alt-shift-cmd-7 = ['move-node-to-workspace 7', 'workspace 4', 'layout tiling']
    ctrl-alt-shift-cmd-8 = ['move-node-to-workspace 8', 'workspace 4', 'layout tiling']
    ctrl-alt-shift-cmd-9 = ['move-node-to-workspace 9', 'workspace 4', 'layout tiling']

    ctrl-alt-shift-semicolon = 'mode service'

[mode.service.binding]
    esc = ['reload-config', 'mode main']
    r = ['flatten-workspace-tree', 'mode main'] # Reset layout
    f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
    backspace = ['close-all-windows-but-current', 'mode main']

    # sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
    #s = ['layout sticky tiling', 'mode main']

    ctrl-alt-shift-cmd-h = ['join-with left', 'mode main']
    ctrl-alt-shift-cmd-j = ['join-with down', 'mode main']
    ctrl-alt-shift-cmd-k = ['join-with up', 'mode main']
    ctrl-alt-shift-cmd-l = ['join-with right', 'mode main']
