unbind C-b
set -g prefix C-a
bind C-a send-prefix

# General config
set -g allow-rename off
set -gq allow-passthrough on
set -g visual-activity off
set -g default-terminal "$TERM"
set -g focus-events on

set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

# Style
set -g status-style 'bg=#32302f'
set -g status-left-length 99
set -g status-right-length 99
set -g status-justify left
set -g pane-border-style 'fg=#59524d'
set -g pane-active-border-style 'fg=#59524d'

# Key bindings
unbind v
unbind s
bind -n M-v selectl even-horizontal
bind -n M-s selectl even-vertical

unbind '"'
unbind %
bind -n M-| splitw -h -c '#{pane_current_path}'
bind -n M-- splitw -v -c '#{pane_current_path}'
bind -n M-c neww -c '#{pane_current_path}'

unbind Up ; unbind Down ; unbind Left ; unbind Right
set -g @tmux-nvim-navigation-keybinding-left 'C-h'
set -g @tmux-nvim-navigation-keybinding-down 'C-j'
set -g @tmux-nvim-navigation-keybinding-up 'C-k'
set -g @tmux-nvim-navigation-keybinding-right 'C-l'
bind -n M-n selectw -n
bind -n M-p selectw -p

unbind C-Up ; unbind C-Down ; unbind C-Left ; unbind C-Right
unbind M-Up ; unbind M-Down ; unbind M-Left ; unbind M-Right
set -g @tmux-nvim-resize false
bind -r -n M-H resizep -L
bind -r -n M-J resizep -D
bind -r -n M-K resizep -U
bind -r -n M-L resizep -R

set -g repeat-time 1000

# Copy mode
setw -g mode-keys vi
unbind -T copy-mode-vi v
bind -T copy-mode-vi 'v' send -X begin-selection

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'joshmedeski/tmux-nerd-font-window-name'
set -g @plugin 'aserowy/tmux.nvim'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

