EDITOR=vim

unbind r
bind r source-file ~/.tmux.conf

# General config
set -g allow-rename off
set -gq allow-passthrough on
set -g visual-activity off

# vim-tpipeline
set -g focus-events on
set -g status-style bg=default
set -g status-left ''
set -g status-right ''
set -g status-left-length 99
set -g status-right-length 99
set -g status-justify absolute-centre

# Key bindings
unbind C-b
set -g prefix C-a
bind C-a send-prefix

unbind -aq -T prefix v
unbind -aq -T prefix s
bind -T prefix v select-layout even-horizontal
bind -T prefix s select-layout even-vertical
unbind '"'
unbind %
bind | split-window -h
bind - split-window -v

set -g repeat-time 1000

# Copy mode
setw -g mode-keys vi
unbind-key -T copy-mode-vi v
bind-key -T copy-mode-vi 'v' send -X begin-selection     # Begin selection in copy mode.
bind-key -T copy-mode-vi 'C-v' send -X rectangle-toggle  # Begin selection in copy mode.
bind-key -T copy-mode-vi 'y' send -X copy-selection      # Yank selection in copy mode.

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'joshmedeski/tmux-nerd-font-window-name'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'aserowy/tmux.nvim'

# navigation
set -g @tmux-nvim-navigation true
set -g @tmux-nvim-navigation-cycle true
set -g @tmux-nvim-navigation-keybinding-left 'C-h'
set -g @tmux-nvim-navigation-keybinding-down 'C-j'
set -g @tmux-nvim-navigation-keybinding-up 'C-k'
set -g @tmux-nvim-navigation-keybinding-right 'C-l'

# resize
set -g @tmux-nvim-resize true
set -g @tmux-nvim-resize-step-x 1
set -g @tmux-nvim-resize-step-y 1
set -g @tmux-nvim-resize-keybinding-left 'M-h'
set -g @tmux-nvim-resize-keybinding-down 'M-j'
set -g @tmux-nvim-resize-keybinding-up 'M-k'
set -g @tmux-nvim-resize-keybinding-right 'M-l'
bind -n C-n next-window
bind -n C-p last-window

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

