#!/bin/bash

DOTFILES=$(pwd)
CONFIGS=(
	".clang-format"
	 ".clangd"
	 ".editorconfig"
	 ".gitconfig"
	 ".lintr"
	 ".tmux.conf"
	 ".vimrc"
	 ".zshrc"
)

for cfg in ${CONFIGS[@]}; do
	if [ -e "$HOME/${cfg}" ]; then
		mv "$HOME/${cfg}" "$HOME/${cfg}-old"
	fi
	ln -s $DOTFILES/${cfg} $HOME/${cfg}
done

# NVIM dependencies (npm needed to install some LSPs)
brew install nvm
nvm install node

# ZSH plugins/themes
brew install autojump eza

git clone https://github.com/zsh-users/zsh-autosuggestions.git $ZSH_CUSTOM/plugins/zsh-autosuggestions

git clone https://github.com/spaceship-prompt/spaceship-prompt.git "$ZSH_CUSTOM/themes/spaceship-prompt" --depth=1
ln -s "$ZSH_CUSTOM/themes/spaceship-prompt/spaceship.zsh-theme" "$ZSH_CUSTOM/themes/spaceship.zsh-theme"

# vim: ft=bash
