#!/bin/bash

DOTFILES=$(pwd)
CONFIGS=(
	".clang-format"
	 ".clangd"
	 ".editorconfig"
	 ".gitconfig"
	 ".lintr"
	 ".tmux.conf"
	 ".vimrc"
	 ".zshrc"
)

for cfg in ${CONFIGS[@]}; do
	if [ -e "$HOME/${cfg}" ]; then
		mv "$HOME/${cfg}" "$HOME/${cfg}-old"
	fi
	ln -s $DOTFILES/${cfg} $HOME/${cfg}
done

# NeoVim dependencies 
brew install nvm lazygit
# npm needed to install some LSPs
nvm install node

# Oh-My-ZSH plugins/themes
brew install autojump eza
git clone https://github.com/zsh-users/zsh-autosuggestions.git $ZSH_CUSTOM/plugins/zsh-autosuggestions
git clone https://github.com/spaceship-prompt/spaceship-prompt.git "$ZSH_CUSTOM/themes/spaceship-prompt" --depth=1
ln -s "$ZSH_CUSTOM/themes/spaceship-prompt/spaceship.zsh-theme" "$ZSH_CUSTOM/themes/spaceship.zsh-theme"

# Setup NeoVim
brew install neovim
git clone git@github.com:N1v3x2/nvim.git ~/.config/nvim

# Setup Kitty
curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin
rm -rf ~/.config/kitty
git clone git@github.com:N1v3x2/kitty.git ~/.config/kitty

# vim: ft=bash
