unbind C-b
set -g prefix C-a
bind C-a send-prefix

# General config
set -g allow-rename off
set -gq allow-passthrough on
set -g visual-activity off
set -g default-terminal "$TERM"
set -g focus-events on
set -g detach-on-destroy off
set -s set-clipboard on
set -s buffer-limit 10
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

########## Styling ##########

# Copy-mode style
set -g mode-style "noattr fg=black bg=yellow"

# Statusline
set -g status-style "fg=#d4be98 bg=#32302f"
set -g status-interval 1

set -g status-left-length 99
set -g status-right-length 99

set -g status-left "#[bright,bg=#a89984,fg=black] \
#(echo #S | tr '[:lower:]' '[:upper:]') #[bg=#32302f] "
set -g status-right "%Y-%m-%d %H:%M #{tmux_mode_indicator}"

# set -g window-status-format "#W"
# set -g window-status-current-format "#W"

# Command prompts
set -g message-style "noattr bg=#282828 fg=#d4be98"
set -g prompt-cursor-color "#d4be98"

# Pane borders
set -g pane-border-style "fg=#59524d"
set -g pane-border-status off
set -g pane-active-border-style "fg=#59524d"

########## Keybinds ##########

# Remove confirmation prompts
unbind x
unbind &
bind x killp
bind & killw

# Window navigation
unbind Up ; unbind Down ; unbind Left ; unbind Right

unbind v
unbind s
unbind M-o
unbind M-s

unbind '"'
unbind %
bind -n M-c neww -c "#{pane_current_path}"

bind h selectp -L
bind j selectp -D
bind k selectp -U
bind l selectp -R

bind -n M-f {
  run "sesh connect \"$(\
  sesh list --hide-attached -d | fzf --tmux \
    --no-sort --border-label ' sesh ' --prompt '> ' --info=hidden \
    --bind 'ctrl-d:execute(tmux kill-session -t {})+reload(sesh list --hide-attached -d)' \
  )\""
}

bind -n M-w {
  run "fzf-worktrees -c '#{pane_current_path}' &>/dev/null"
}

unbind C-Up
unbind C-Down
unbind C-Left
unbind C-Right
unbind M-Up
unbind M-Down
unbind M-Left
unbind M-Right

set -g repeat-time 1000

# Copy mode
setw -g mode-keys vi
unbind -T copy-mode-vi v
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection
bind -T copy-mode-vi Y send -X copy-end-of-line

# Plugins
set -g @plugin "tmux-plugins/tpm"
set -g @plugin "tmux-plugins/tmux-sensible"
set -g @plugin 'MunifTanjim/tmux-mode-indicator'
set -g @plugin 'MunifTanjim/tmux-suspend'

set -g @mode_indicator_prefix_mode_style 'bright,bg=blue,fg=black'
set -g @mode_indicator_copy_mode_style 'bright,bg=yellow,fg=black'
set -g @mode_indicator_sync_mode_style 'bright,bg=red,fg=black'
set -g @mode_indicator_empty_mode_style 'bright,bg=#a89984,fg=black'

run "~/.tmux/plugins/tpm/tpm"

# vim: ft=tmux
