unbind C-b
set -g prefix C-a
bind C-a send-prefix

# General config
set -g allow-rename off
set -gq allow-passthrough on
set -g visual-activity off
set -g default-terminal "$TERM"
set -g focus-events on
set -g detach-on-destroy off
set -s set-clipboard on
set -s buffer-limit 10
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

# Copy-mode style
set -g mode-style "noattr fg=black bg=#e78a4e"

# Statusline
set -g status-style "fg=#d4be98 bg=#32302f"
set -g status-interval 1
set -g message-style "noattr bg=black fg=#e78a4e"

set -g status-left " #S "
set -g status-left-length 99

set -g status-right ""
set -g status-right-length 99

set -g window-status-format ""
set -g window-status-current-format ""

# Pane borders
set -g pane-border-style "fg=#59524d"
set -g pane-border-status off
set -g pane-active-border-style "fg=#59524d"

# Keybinds

# Remove confirmation prompts
unbind x
unbind &
bind x killp
bind & killw

# Window navigation
unbind Up ; unbind Down ; unbind Left ; unbind Right

unbind v
unbind s
unbind M-o
unbind M-s

unbind '"'
unbind %
bind -n M-c neww -c "#{pane_current_path}"

bind h selectp -L
bind j selectp -D
bind k selectp -U
bind l selectp -R

bind -n M-f {
  set -g cursor-style bar
  run "sesh connect \"$(\
  sesh list --hide-attached -d | fzf --tmux \
    --no-sort --border-label ' sesh ' --prompt '> ' --info=hidden \
    --bind 'ctrl-d:execute(tmux kill-session -t {})+reload(sesh list --hide-attached -d)' \
  )\""
  set -g cursor-style block
}

bind -n M-w {
  set -g cursor-style bar
  run "fzf-worktrees -c '#{pane_current_path}' &>/dev/null"
  set -g cursor-style block
}

unbind C-Up
unbind C-Down
unbind C-Left
unbind C-Right
unbind M-Up
unbind M-Down
unbind M-Left
unbind M-Right

set -g repeat-time 1000

unbind 0
unbind 1
unbind 2
unbind 3
unbind 4
unbind 5
unbind 6
unbind 7
unbind 8
unbind 9
unbind -n M-1
unbind -n M-2
unbind -n M-3
unbind -n M-4
unbind -n M-5
unbind -n M-6
unbind -n M-7
unbind -n M-8
unbind -n M-9

# Copy mode
setw -g mode-keys vi
unbind -T copy-mode-vi v
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection
bind -T copy-mode-vi Y send -X copy-end-of-line

bind -n C-, copy-mode \; send -X -N 2 search-backward ".* » .*" \; send -X scroll-top
bind -T copy-mode-vi C-, send -X search-backward ".* » .*" \; send -X scroll-top
bind -T copy-mode-vi c-. send -X search-forward ".* » .*" \; send -X scroll-top

bind -T copy-mode-vi C-p send -X search-backward "^\(gdb\) .*" \; send -X scroll-top
bind -T copy-mode-vi C-n send -X search-forward "^\(gdb\) .*" \; send -X scroll-top

# Plugins
set -g @plugin "tmux-plugins/tpm"
set -g @plugin "tmux-plugins/tmux-sensible"
set -g @plugin "tmux-plugins/tmux-resurrect"
set -g @plugin "tmux-plugins/tmux-continuum"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run "~/.tmux/plugins/tpm/tpm"

# vim: ft=tmux
