;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;==========================================================

[colors]
background = #2d353b
background-alt = #3d484d
foreground = #d3c6aa
primary = #a7c080
secondary = #7fbbb3
alert = #e67e80
disabled = #7a8478

[bar/main]
width = 100%
height = 24pt
radius = 0

dpi = ${xrdb:Xft.dpi:144}

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 2pt

border-size = 8pt
border-bottom-size = 0pt
border-color = #00000000

padding-left = 0
padding-right = 1

module-margin = 1

separator = |
separator-foreground = ${colors.disabled}

font-0 = JetbrainsMono Nerd Font:weight=SemiBold;2

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

wm-name = i3
wm-restack = i3

modules-left = xworkspaces xwindow
modules-right = pulseaudio memory date

[module/xworkspaces]
type = internal/xworkspaces

label-active = %name%
label-active-background = ${colors.background-alt}
label-active-underline= ${colors.primary}
label-active-padding = 1

label-occupied = %name%
label-occupied-padding = 1

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

reverse-scroll = true

[module/xwindow]
type = internal/xwindow
label = %title:0:100:...%

[module/pulseaudio]
type = internal/pulseaudio

use-ui-max = false
format-volume = %{F#a7c080}<ramp-volume> %{F-}<label-volume>

label-volume = %percentage%%

label-muted = 󰖁 muted
label-muted-foreground = ${colors.disabled}

ramp-volume-0 = 󰕿
ramp-volume-1 = 󰖀
ramp-volume-2 = 󰕾

[module/memory]
type = internal/memory
interval = 2
format-prefix = "  "
format-prefix-foreground = ${colors.primary}
label = %used%

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = "  "
format-prefix-foreground = ${colors.primary}
label = %percentage%%

[module/date]
type = internal/date
interval = 1

format = %{F#a7c080}󰃭 %{F-}<label>

date = %a %b %d %I:%M %p
date-alt = %I:%M %p

label = %date%

[network-base]
type = internal/network
interval = 5
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-disconnected = %{F#dbbc7f}%ifname%%{F#707880} disconnected

[module/wlan]
inherit = network-base
interface-type = wireless
label-connected = %{F#dbbc7f}%ifname%%{F-} %essid%

[module/eth]
inherit = network-base
interface-type = wired
label-connected = %{F#dbbc7f}%ifname%%{F-} %local_ip%

[settings]
screenchange-reload = true
pseudo-transparency = true

; vim:ft=dosini
